apiVersion: v1
kind: Service
metadata:
  name: {{ template "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: {{ template "laravel.fullname" . }}
    {{- if .Values.websocket.enabled }}
    - name: {{ template "laravel.fullname" . }}-websocket
      port: {{ .Values.websocket.port }}
      protocol: TCP
      targetPort: {{ .Values.websocket.port }}
    {{- end }}
  selector:
    app: {{ template "laravel.environment" . }}