apiVersion: v1
kind: Secret
metadata:
  name: {{ template "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.smtp.enabled }}
  MAIL_PASSWORD: {{ .Values.smtp.password |b64enc | quote }}
  {{- end -}}
  {{- if .Values.mysql.enabled }}
  DB_PASSWORD: {{ .Values.mysql.mysqlPassword |b64enc | quote }}
  {{- else if .Values.sqlproxy.enabled }}
  DB_PASSWORD: {{ .Values.sqlproxy.sqlPassword |b64enc | quote }}
  {{- end -}}